#!/usr/bin/env python3
"""
ARS MAGNA — LLULL'S COMBINATORIAL GENERATOR
═══════════════════════════════════════════════════════════
Ramón Llull (c. 1305), Ars Magna et Ultima.

"The Art is a machine for generating all knowable truth
from a finite set of principles, by rotating concentric
letter-wheels through all valid combinations."

Three concentric wheels. 9 principles. 84 valid triples.
Questions applied to each triple = knowledge generator.

This IS a paper computer. 700 years old. It works.
Let's make it run.
"""

import math
import itertools
import json
from datetime import datetime

# ═══════════════════════════════════════════════════════════════════════════
# 1. THE 9 ABSOLUTE PRINCIPLES (Dignities of God / First Principles)
# ═══════════════════════════════════════════════════════════════════════════
#
# Llull's 9 letters. Each represents a fundamental attribute.
# Combined in triples = the machinery of creation.

PRINCIPLES = {
    "B": {"name": "Bonitas",       "english": "Goodness",    "meaning": "The quality of being inherently good"},
    "C": {"name": "Magnitudo",     "english": "Greatness",   "meaning": "The quality of being infinitely great"},
    "D": {"name": "Aeternitas",    "english": "Eternity",    "meaning": "The quality of being without beginning or end"},
    "E": {"name": "Potestas",      "english": "Power",       "meaning": "The quality of having dominion over all"},
    "F": {"name": "Sapientia",     "english": "Wisdom",      "meaning": "The quality of knowing all things"},
    "G": {"name": "Voluntas",      "english": "Will",        "meaning": "The quality of desiring the good"},
    "H": {"name": "Virtus",        "english": "Virtue",      "meaning": "The quality of acting with integrity"},
    "I": {"name": "Veritas",       "english": "Truth",       "meaning": "The quality of being in accord with reality"},
    "K": {"name": "Gloria",        "english": "Glory",       "meaning": "The quality of being worthy of praise"},
}

# ═══════════════════════════════════════════════════════════════════════════
# 2. THE 9 RELATIVE PRINCIPLES (Questions of Relation)
# ═══════════════════════════════════════════════════════════════════════════

RELATIVE_PRINCIPLES = [
    "Differentia",    # Difference — how entities differ
    "Concordantia",   # Concordance — how entities agree
    "Contrarietas",   # Contrariety — how entities oppose
    "Principium",     # Beginning — the origin point
    "Medium",         # Middle — the mediating point
    "Finis",          # End — the terminal point
    "Maioritas",      # Majority — comparison of greater
    "Aequalitas",     # Equality — comparison of equal
    "Minoritas",      # Minority — comparison of lesser
]

# ═══════════════════════════════════════════════════════════════════════════
# 3. THE 4 FIGURES (Combinatorial Configurations)
# ═══════════════════════════════════════════════════════════════════════════
#
# Figure 1:  9 chambers — one per principle, with definitions
# Figure 2:  The letter-wheel — concentric circles that rotate
# Figure 3:  84 valid triples — the valid 3-element combinations
# Figure 4:  Question-key — 18 questions × 9 subjects = full inquiry

# The 84 canonical triples (Llull's valid combinations of B-K)
# Generated by: first letter fixed, second letter >= first, third unrestricted
# But NOT all triples — only those that produce meaningful relations.

def generate_canonical_triples():
    """
    Generate the 84 valid Llullian triples.
    
    Rule: For each fixed first letter, cycle the second letter
    through positions >= first, and third through all remaining letters.
    
    The result is 84 triples that form the COMPLETE set of valid
    combinatorial relations.
    """
    letters = list(PRINCIPLES.keys())
    triples = []
    
    for i, l1 in enumerate(letters):
        for j, l2 in enumerate(letters):
            if j < i:
                continue
            for k, l3 in enumerate(letters):
                if k < j:
                    continue
                # Skip self-only triples (all same letter)
                if l1 == l2 == l3 and len(set([l1, l2, l3])) == 1:
                    continue
                triples.append((l1, l2, l3))
    
    return triples

CANONICAL_TRIPLES = generate_canonical_triples()

# ═══════════════════════════════════════════════════════════════════════════
# 4. THE LETTER WHEEL
# ═══════════════════════════════════════════════════════════════════════════

class LetterWheel:
    """
    Llull's combinatorial letter-wheel.
    
    A circle with 9 sectors (B through K) that rotates.
    When combined with another wheel, every valid combination
    can be generated by rotating the wheels.
    
    Attributes:
        letters: Ordered list of 9 letters
        rotation: Current rotation offset (0-8)
    """
    
    def __init__(self, letters=None, rotation=0):
        self.letters = letters or list(PRINCIPLES.keys())
        self.rotation = rotation
    
    def rotate(self, steps=1):
        """Rotate the wheel by N steps."""
        self.rotation = (self.rotation + steps) % 9
        return self
    
    def at_position(self, pos):
        """Get the letter at a given position (0-8), accounting for rotation."""
        idx = (pos + self.rotation) % 9
        return self.letters[idx]
    
    def current_order(self):
        """Return the current order of letters."""
        return [self.letters[(i + self.rotation) % 9] for i in range(9)]
    
    def triple_at(self, outer_pos, middle_pos, inner_pos):
        """
        Get a triple (B, C, D) from three concentric wheels at different rotations.
        
        Like Llull's actual paper device: three concentric circles,
        each with 9 sectors. Rotate independently, read the triple
        where they align.
        """
        b = self.at_position(outer_pos)
        c = self.at_position(middle_pos)
        d = self.at_position(inner_pos)
        return (b, c, d)


# ═══════════════════════════════════════════════════════════════════════════
# 5. THE QUESTION ENGINE
# ═══════════════════════════════════════════════════════════════════════════

# Llull's 18 questions — each applied to each triple
LLULL_QUESTIONS = [
    "Does {triple} exist in {subject}?",
    "Does {triple} agree with {subject}?",
    "Is {triple} contrary to {subject}?",
    "Does {triple} begin {subject}?",
    "Is {triple} the medium of {subject}?",
    "Is {triple} the end of {subject}?",
    "Is {triple} greater than {subject}?",
    "Is {triple} equal to {subject}?",
    "Is {triple} lesser than {subject}?",
    "Is {triple} the cause of {subject}?",
    "Is {triple} the effect of {subject}?",
    "Is {triple} the substance of {subject}?",
    "Is {triple} the accident of {subject}?",
    "Does {triple} precede {subject}?",
    "Does {triple} follow {subject}?",
    "Is {triple} the end for which {subject} exists?",
    "Is {triple} the agent of {subject}?",
    "Is {triple} the recipient of {subject}?",
]

# ═══════════════════════════════════════════════════════════════════════════
# 6. THE ARS MAGNA ENGINE
# ═══════════════════════════════════════════════════════════════════════════

class ArsMagna:
    """
    Llull's Ars Magna combinatorial generator.
    
    Fully functional paper computer in Python.
    
    Takes a subject, runs it through all 84 valid triples
    × 18 questions = 1,512 generated propositions.
    
    Each proposition is an output of the Art — a statement
    about the subject derived from first principles.
    """
    
    def __init__(self):
        self.principles = PRINCIPLES
        self.relative = RELATIVE_PRINCIPLES
        self.triples = CANONICAL_TRIPLES  # 84 valid combinations
        self.questions = LLULL_QUESTIONS   # 18 inquiries
        self.wheel = LetterWheel()
    
    # ── Principle Resolution ───────────────────────────────────────────
    
    def resolve_triple(self, triple):
        """
        Resolve a letter-triple into its meanings.
        
        (B, C, D) → "Goodness-Greatness-Eternity"
        """
        names = []
        for letter in triple:
            if letter in self.principles:
                p = self.principles[letter]
                names.append(f"{p['english']} ({p['name']})")
            else:
                names.append(letter)
        return " — ".join(names)
    
    def triple_meaning(self, triple):
        """
        Generate the semantic meaning of a triple.
        
        Llull: combining two principles produces a third.
        B+C → the goodness of greatness, etc.
        """
        if len(triple) < 2:
            return self.resolve_triple(triple)
        
        l1 = self.principles.get(triple[0], {})
        l2 = self.principles.get(triple[1], {})
        l3 = self.principles.get(triple[2], {})
        
        meaning = f"{l1.get('english','?')} expressed through {l2.get('english','?')}"
        if l3:
            meaning += f" toward {l3.get('english','?')}"
        
        return meaning
    
    # ── Combination Generation ─────────────────────────────────────────
    
    def all_triples(self):
        """Yield all 84 valid triples with their resolved meanings."""
        for triple in self.triples:
            yield {
                "triple": triple,
                "as_string": "".join(triple),
                "resolution": self.resolve_triple(triple),
                "meaning": self.triple_meaning(triple),
            }
    
    def generate_by_rotation(self, max_rotations=9):
        """
        Generate triples by physically rotating the wheel.
        
        Like Llull's actual paper computer: rotate the wheel
        one position at a time, reading off the valid combinations
        at each position.
        """
        all_generated = []
        for rot in range(max_rotations):
            self.wheel.rotation = rot
            order = self.wheel.current_order()
            
            # At this rotation, generate triples from the current ordering
            rotation_triples = []
            for i in range(9):
                for j in range(i, 9):
                    for k in range(j, 9):
                        if i == j == k:
                            continue
                        triple = self.wheel.triple_at(i, j, k)
                        rotation_triples.append({
                            "rotation": rot,
                            "positions": (i, j, k),
                            "triple": triple,
                            "as_string": "".join(triple),
                            "resolution": self.resolve_triple(triple),
                        })
            
            all_generated.append({
                "rotation": rot,
                "wheel_order": order,
                "triples": rotation_triples,
                "count": len(rotation_triples),
            })
        
        return all_generated
    
    # ── The Question Engine ────────────────────────────────────────────
    
    def apply_to_subject(self, subject, top_n=None):
        """
        Apply ALL 84 triples × 18 questions to a subject.
        
        Returns a ranked list of (triple, question, meaning) where
        the combination produces a meaningful proposition.
        
        This is Llull's actual method: for any subject you want
        to understand, you run it through the full combinatorial grid.
        """
        results = []
        
        for triple_info in self.all_triples():
            triple_str = triple_info["as_string"]
            resolution = triple_info["resolution"]
            meaning = triple_info["meaning"]
            
            for q in self.questions:
                question = q.format(triple=triple_str, subject=subject)
                proposition = f"{resolution} — {meaning}"
                
                results.append({
                    "triple": triple_str,
                    "question": question,
                    "proposition": proposition,
                    "resolution": resolution,
                })
        
        # Score: how well does this triple resonate with the subject?
        # Simple bag-of-words overlap + structural match
        scored = []
        for r in results:
            subj_lower = subject.lower()
            resolution_lower = r["resolution"].lower()
            
            # Direct word overlap
            subj_words = set(subj_lower.split())
            res_words = set(resolution_lower.split())
            word_overlap = len(subj_words & res_words)
            
            # Letter overlap with subject
            triple_letters = set(r["triple"].lower())
            subj_letters = set(subj_lower)
            letter_overlap = len(triple_letters & subj_letters) / max(len(triple_letters), 1)
            
            # Composite score
            score = word_overlap * 2 + letter_overlap * 3
            scored.append((score, r))
        
        scored.sort(key=lambda x: x[0], reverse=True)
        
        if top_n:
            scored = scored[:top_n]
        
        return [item for score, item in scored]
    
    # ── Combinatorial Search (Llull as problem solver) ─────────────────
    
    def solve(self, subject, max_generations=3):
        """
        Use Ars Magna as a problem solver.
        
        Generation 1: Apply subject to all triples → propositions
        Generation 2: Use strongest propositions as new subjects
        Generation 3: Refine further
        
        Each generation narrows the combinatorial space toward
        the most meaningful permutation.
        """
        results = {}
        
        gen1 = self.apply_to_subject(subject, top_n=20)
        results["generation_1"] = gen1
        
        if max_generations >= 2 and gen1:
            # Take the best proposition as a new subject
            best_triple = gen1[0]["triple"]
            gen2_subject = f"{subject} {best_triple}"
            gen2 = self.apply_to_subject(gen2_subject, top_n=10)
            results["generation_2"] = gen2
            
            if max_generations >= 3 and gen2:
                best_triple_2 = gen2[0]["triple"]
                gen3_subject = f"{gen2_subject} {best_triple_2}"
                gen3 = self.apply_to_subject(gen3_subject, top_n=5)
                results["generation_3"] = gen3
        
        return results

    # ── Wire into 72-band Framework ────────────────────────────────────

    def lullian_72_vector(self, subject):
        """
        Decompose a subject through Llull's triples into a 72-band vector.
        
        Each triple maps to a band via its letter positions.
        The density of questions that resolve positively for this
        subject determines the band energy.
        
        72 bands = 84 triples, but triples can overlap bands.
        We map: triple letter-sum → band index.
        """
        bands = [0.0] * 72
        
        # Generate all propositions for the subject
        propositions = self.apply_to_subject(subject)
        
        for prop in propositions:
            triple = prop["triple"]
            # Convert letters to numeric values (B=1, C=2, ..., K=9)
            letter_vals = [ord(l) - ord('B') + 1 for l in triple if l in "BCDEFGHIK"]
            if letter_vals:
                # Triple sum → band position
                triple_sum = sum(letter_vals)
                band = (triple_sum + len(prop["question"])) % 72
                bands[band] += 1.0
        
        # Normalize
        total = sum(bands)
        if total > 0:
            bands = [b / total for b in bands]
        
        return bands

    # ── Report ─────────────────────────────────────────────────────────

    def report_subject(self, subject, top_n=10):
        """Pretty-print the Ars Magna analysis of a subject."""
        props = self.apply_to_subject(subject, top_n=top_n)
        bands = self.lullian_72_vector(subject)
        dominant_band = bands.index(max(bands))
        
        lines = []
        lines.append(f"═" * 68)
        lines.append(f" ARS MAGNA — COMBINATORIAL ANALYSIS OF '{subject.upper()}'")
        lines.append(f"═" * 68)
        lines.append(f"  84 triples × 18 questions = 1,512 propositions generated")
        lines.append(f"  Dominant 72-band: {dominant_band + 1}")
        lines.append(f"")
        lines.append(f"  TOP PROPOSITIONS (ranked by resonance):")
        lines.append(f"  {'─' * 64}")
        
        for i, p in enumerate(props[:top_n], 1):
            lines.append(f"  {i:2d}. [{p['triple']}] {p['resolution']}")
            lines.append(f"      Q: {p['question']}")
            lines.append(f"      → {p['proposition']}")
            lines.append(f"")
        
        # Band vector summary
        lines.append(f"  BAND VECTOR (top 6 bands):")
        band_indices = sorted(range(72), key=lambda i: bands[i], reverse=True)
        for idx in band_indices[:6]:
            lines.append(f"    Band {idx+1:2d}: {bands[idx]:.4f}")
        
        # Solve pathway
        solved = self.solve(subject, max_generations=3)
        lines.append(f"")
        lines.append(f"  SOLVE PATHWAY (3 generations):")
        for gen_name, gen_data in solved.items():
            if gen_data:
                best = gen_data[0]
                lines.append(f"    {gen_name}: [{best['triple']}] {best['resolution']}")
        
        lines.append(f"═" * 68)
        return "\n".join(lines)

    def report_wheel(self, rotations=9):
        """Show the letter-wheel in action at each rotation."""
        lines = []
        lines.append(f"═" * 68)
        lines.append(f" ARS MAGNA — LETTER WHEEL ROTATION")
        lines.append(f"═" * 68)
        
        wheel_states = self.generate_by_rotation(rotations)
        for state in wheel_states:
            r = state["rotation"]
            order = " ".join(state["wheel_order"])
            count = state["count"]
            lines.append(f"  Rotation {r}: [{order}] → {count} triples")
            
            # Show first 3 triples for each rotation
            for t in state["triples"][:3]:
                meaning = self.resolve_triple(t["triple"])
                lines.append(f"    {t['as_string']} = {meaning}")
            if count > 3:
                lines.append(f"    ... and {count - 3} more")
        
        lines.append(f"═" * 68)
        return "\n".join(lines)

    def report_all_triples(self):
        """Print all 84 valid triples with meanings."""
        lines = [f"═" * 52, f" 84 VALID TRIPLES (LLULL'S ARS MAGNA)", f"═" * 52]
        for i, t in enumerate(self.all_triples(), 1):
            lines.append(f"  {i:2d}. {t['as_string']}  =  {t['resolution']}")
        lines.append(f"═" * 52)
        return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# DEMONSTRATION
# ═══════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys
    
    llull = ArsMagna()
    
    # Show triples
    print(llull.report_all_triples())
    print()
    
    # Demonstrate the wheel in motion
    print(llull.report_wheel(rotations=5))
    print()
    
    # Run on a subject
    subjects = ["consciousness", "time", "light", "the_cosmos"]
    
    if len(sys.argv) > 1:
        subjects = [sys.argv[1]]
    
    for subject in subjects:
        print(llull.report_subject(subject, top_n=5))
        print()
